server:
  port: ${SERVER_PORT:8443}
  ssl:
    enabled: ${SSL_ENABLED:true}
    key-store: ${SSL_KEY_STORE:classpath:keystore.p12}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS:dosw-library}

spring:
  profiles:
    active: mongo
  autoconfigure:
    exclude:
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://ders14028_db_user:Ders.210021mdt@cluster0.1p8nobv.mongodb.net/?appName=Cluster0}
      database: dosw_library

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000